name: CI-Contract

on: [push, pull_request]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["20.x"]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Node ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      working-directory: dqpu-contract
      run: npm install

    - name: Run tests
      working-directory: dqpu-contract
      run: npm run test

